#Mini Project Kasus 2
#Traveling Salesman Problem With Genetic Algorithm

##Import Library

In [1]:
import numpy as np 
import random
from array import *
import matplotlib.pyplot as plt


#DATABASE Berlin52


In [2]:
# Open input file
infile = open('berlin52.tsp', 'r')

# Read instance header
Name = infile.readline().strip().split()[1] # NAME
FileType = infile.readline().strip().split()[1] # TYPE
Comment = infile.readline().strip().split()[1] # COMMENT
Dimension = infile.readline().strip().split()[1] # DIMENSION
EdgeWeightType = infile.readline().strip().split()[1] # EDGE_WEIGHT_TYPE
infile.readline()

# Read node list
nodelist = []
N = int(Dimension)
for i in range(0, N):
    x,y = infile.readline().strip().split()[1:]
    nodelist.append([float(x), float(y)])

# Close input file
infile.close()

print (nodelist)

[[565.0, 575.0], [25.0, 185.0], [345.0, 750.0], [945.0, 685.0], [845.0, 655.0], [880.0, 660.0], [25.0, 230.0], [525.0, 1000.0], [580.0, 1175.0], [650.0, 1130.0], [1605.0, 620.0], [1220.0, 580.0], [1465.0, 200.0], [1530.0, 5.0], [845.0, 680.0], [725.0, 370.0], [145.0, 665.0], [415.0, 635.0], [510.0, 875.0], [560.0, 365.0], [300.0, 465.0], [520.0, 585.0], [480.0, 415.0], [835.0, 625.0], [975.0, 580.0], [1215.0, 245.0], [1320.0, 315.0], [1250.0, 400.0], [660.0, 180.0], [410.0, 250.0], [420.0, 555.0], [575.0, 665.0], [1150.0, 1160.0], [700.0, 580.0], [685.0, 595.0], [685.0, 610.0], [770.0, 610.0], [795.0, 645.0], [720.0, 635.0], [760.0, 650.0], [475.0, 960.0], [95.0, 260.0], [875.0, 920.0], [700.0, 500.0], [555.0, 815.0], [830.0, 485.0], [1170.0, 65.0], [830.0, 610.0], [605.0, 625.0], [595.0, 360.0], [1340.0, 725.0], [1740.0, 245.0]]


In [3]:
for i in nodelist:
    for j in i:
        print(j,end = " ")
    print()

jumlahLokasi =  len(nodelist)   
print(jumlahLokasi)

565.0 575.0 
25.0 185.0 
345.0 750.0 
945.0 685.0 
845.0 655.0 
880.0 660.0 
25.0 230.0 
525.0 1000.0 
580.0 1175.0 
650.0 1130.0 
1605.0 620.0 
1220.0 580.0 
1465.0 200.0 
1530.0 5.0 
845.0 680.0 
725.0 370.0 
145.0 665.0 
415.0 635.0 
510.0 875.0 
560.0 365.0 
300.0 465.0 
520.0 585.0 
480.0 415.0 
835.0 625.0 
975.0 580.0 
1215.0 245.0 
1320.0 315.0 
1250.0 400.0 
660.0 180.0 
410.0 250.0 
420.0 555.0 
575.0 665.0 
1150.0 1160.0 
700.0 580.0 
685.0 595.0 
685.0 610.0 
770.0 610.0 
795.0 645.0 
720.0 635.0 
760.0 650.0 
475.0 960.0 
95.0 260.0 
875.0 920.0 
700.0 500.0 
555.0 815.0 
830.0 485.0 
1170.0 65.0 
830.0 610.0 
605.0 625.0 
595.0 360.0 
1340.0 725.0 
1740.0 245.0 
52


###Inisialisasi Populasi secara acak

###Array P diinisialisasi sebagai array integer

###Solusi awal dibuat dengan random permutation


In [4]:
def initPopulasi(ukuranPopulasi,jumlahLokasi):
  P = np.empty((ukuranPopulasi,jumlahLokasi))
  P = P.astype('int')
  for i in range(ukuranPopulasi):
    I = np.random.permutation(jumlahLokasi)
    for j in range(jumlahLokasi):
      P[i][j]=I[j]
  return P

ukuranPopulasi = 10
P = initPopulasi (ukuranPopulasi,jumlahLokasi)
print("Inisialisasi Populasi : ",P)

Inisialisasi Populasi :  [[47 43 36 38 28 37 30 34  2 50 22  9 29  7 24 40 25 31 10 41 12 11 39 27
  26 14  5 17  6  3 18 19 51  1 42 45 49  4 23 20 33 32 48 21 35 16 44 15
   0  8 13 46]
 [19 47  4 41 28  2 32 13 39  0 46 23 14 40  1 33 25 45 50 44 22 15 43 12
  18 21 30 42 36 17  9 31 16  5  3  6  8 34 20 29 48 51 26 35 49  7 24 37
  10 11 27 38]
 [10 14 17  9 26 46  6 29 38  0 48 13 30 44  8 21 47  7 40 28 51  2 37 11
  49 43 33 35 22 19 20  5 41 34 23 25 16 50  1 12 36 32 45  4 39 18  3 31
  27 24 42 15]
 [32  3 29 48 17 31 49  2 20  4 33 27 40  5 19 11 43  0 34 51 13 12 44  7
  26 16  6 35 42 30 41 24 23 18 39 21 14  1 50 38 10  9 15 22 36 28 25 47
   8 45 37 46]
 [ 3 34 35 46 20 14 51 17 42  7 27 23 43 12 38 24 22 47 26 37  4 28 18 15
  48  9 21 11 16  0 19 40 29  6 25 50 32 30 33 36 44 45 10 39  2 13 49  5
   8 31 41  1]
 [46 31 40 41 11 51 28 10 25 43 14  9 37 33 44  4 39 49 22 38 36 42 17 15
  45 34 30  5 24 48 35 23  2 16  6 12  8  0 18 21 47 26 19 27 32  3 20 13
   7 50 29  

###Membuat Fungsi Objektif

###Jarak yang diukur adalah Jarak Euclidian

In [5]:
def fungsiObjectif(populasi,nodelist):
  sz = populasi.shape
  ukuranPopulasi = sz[0]
  jumlahLokasi = sz[1]

  matrikJarak = np.empty((ukuranPopulasi))
  matrikJarak = matrikJarak.astype('float')
  n = len(nodelist)

  for i in range(ukuranPopulasi):
    jarak = 0
    for j in range(n-1):
      jrkX = nodelist[populasi[i][j]][0]-nodelist[populasi[i][j+1]][0]
      jrkY = nodelist[populasi[i][j]][1]-nodelist[populasi[i][j+1]][1]
      d = np.sqrt(jrkX**2 + jrkY**2 )   
      jarak = jarak  + d
      
    dn =  np.sqrt((nodelist[populasi[i][n-1]][0]-nodelist[populasi[i][0]][0])**2+ (nodelist[populasi[i][n-1]][1]-nodelist[populasi[i][0]][1])**2 )
    jarak = jarak  + dn
    matrikJarak[i] = jarak

  return matrikJarak

fitP = fungsiObjectif(P,nodelist)
print(fitP)

[31604.74255371 28667.54138156 30314.03581178 29134.18462439
 30732.99628756 28543.27049004 31766.1959406  30838.14788264
 29199.34543807 30640.93261067]


###Seleksi menggunakan Metode Tournamen

###Ukuran Tournamen k = 2

###Jumlah Induk yang dipilih adalah 2

In [6]:
def seleksi (P,fsObj):
  jmlInduk = 2
  sz = P.shape
  ukuranPopulasi = sz[0]
  jumlahLokasi = sz[1]

  Induk = np.empty((jmlInduk,jumlahLokasi))
  Induk = Induk.astype('int')
  
  for i in range (2):
    #memilih dua individu secara acak 
    r1 = random.randint(0,ukuranPopulasi-1)
    r2 = random.randint(0,ukuranPopulasi-1)
    
    if  fsObj[r1] < fsObj [r2]:
      for j in range(jumlahLokasi):
        Induk [i][j] = P[r1][j]
    else:
      for j in range(jumlahLokasi):
        Induk [i][j] = P[r2][j]
  return Induk

Induk = seleksi(P,fitP)
print(Induk)

[[10 14 17  9 26 46  6 29 38  0 48 13 30 44  8 21 47  7 40 28 51  2 37 11
  49 43 33 35 22 19 20  5 41 34 23 25 16 50  1 12 36 32 45  4 39 18  3 31
  27 24 42 15]
 [32 30 44  4 36 13 38 42 18 26 21 37  9 46 15  8 50 51 16 17 20 29 49 35
  24 40  7  1  0 28  6 10 39  2  5 43 45 48 12 22 41 23  3 14 19 34 47 33
  27 31 11 25]]


###Rekombinasi menggunakan Metode Order Crossover (OX) Jumlah anak yang dihasilkan adalah 2
###Crossover 

In [7]:
def PMX(Induk):
  Induk = seleksi(P,fitP)
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  I1 = np.empty((kol))
  I2 = np.empty((kol))
  A1 = np.empty((kol))
  A2 = np.empty((kol))
  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  for i in range(kol):
    I1[i]=Induk[0][i]
    I2[i]=Induk[1][i]

  r1 = random.randint(1,kol-2)

  for i0 in range(r1): 
    A1[i0] = I1[i0]
    A2[i0] = I2[i0]

  batasCek1 = r1
  batasCek2 = r1

  for i in range(kol):
    m = (i+r1)%kol

    n1 = I1[m] 
    n2 = I2[m]

    #mengecek apakah Lokasi tertentu sudah ada di anak

    idxAda1 = 0
    idxAda2 = 0
    for j1 in range(batasCek1): 
      
      if batasCek1>(kol):
        idxAda1 = 1

      if A1[j1] == n2: 
        idxAda1 = 1
            
    for j2 in range(batasCek2): 
      
      if batasCek2>(kol):
        idxAda2 = 1

      if A2[j2] == n1: 
        idxAda2 = 1

    if idxAda1 == 0:
      A1[batasCek1] = n2
      batasCek1 = batasCek1 +1
   
    if idxAda2 == 0:
      A2[batasCek2] = n1
      batasCek2 = batasCek2 +1
   
  for i in range(kol):
    Anak[0][i]=A1[i]
    Anak[1][i]=A2[i]

  return Anak

AnakCX = PMX(Induk)
print("Anak :",AnakCX)

Anak : [[46 31 40 41 11 51 28 10 25 43 14  9 37 33 44  4 39 49 22 38 36 42  7 26
  16  6 35 30 24 23 18 21  1 50 15 47  8 45 32  3 29 48 17  2 20 27  5 19
   0 34 13 12]
 [32  3 29 48 17 31 49  2 20  4 33 27 40  5 19 11 43  0 34 51 13 12 15 45
  30 24 35 23 16  6  8 18 21 47 26  7 50  1 46 41 28 10 25 14  9 37 44 39
  22 38 36 42]]


###Mutasi dengan Swap

###Index Lokasi yang di Swap pada kedua anak sama

In [8]:
def MutasiSwap(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  Anak = Induk

  r1 = random.randint(0,kol-1)
  r2 = random.randint(0,kol-1)

  while r1 == r2:
    r2 = random.randint(0,kol-1)
  
  if r1 < r2:
    rs1 = r1
    rs2 = r2
  else:
    rs1 = r2
    rs2 = r1

  I1rs1 = Induk [0][rs1]
  I1rs2 = Induk [0][rs2]
  I2rs1 = Induk [1][rs1]
  I2rs2 = Induk [1][rs2]

  Anak[0][rs1] = I1rs2
  Anak[0][rs2] = I1rs1
  Anak[1][rs1] = I2rs2
  Anak[1][rs2] = I2rs1

  return Anak

print("AnakCX :",AnakCX)
AnakM = MutasiSwap(AnakCX)
print("AnakM :",AnakM)

AnakCX : [[46 31 40 41 11 51 28 10 25 43 14  9 37 33 44  4 39 49 22 38 36 42  7 26
  16  6 35 30 24 23 18 21  1 50 15 47  8 45 32  3 29 48 17  2 20 27  5 19
   0 34 13 12]
 [32  3 29 48 17 31 49  2 20  4 33 27 40  5 19 11 43  0 34 51 13 12 15 45
  30 24 35 23 16  6  8 18 21 47 26  7 50  1 46 41 28 10 25 14  9 37 44 39
  22 38 36 42]]
AnakM : [[46 31 40 41 11 51 28 10 25 43 14  9 37 33 44  4 39 49 22 38 36 42  7 26
  16  6  1 30 24 23 18 21 35 50 15 47  8 45 32  3 29 48 17  2 20 27  5 19
   0 34 13 12]
 [32  3 29 48 17 31 49  2 20  4 33 27 40  5 19 11 43  0 34 51 13 12 15 45
  30 24 21 23 16  6  8 18 35 47 26  7 50  1 46 41 28 10 25 14  9 37 44 39
  22 38 36 42]]


###Elitism (steady state replacement)

In [9]:
def Elitism(P,Anak,fitP,fitAnak):
  szP = P.shape
  brsP = szP[0]
  kolP = szP[1]
  szA = Anak.shape
  brsA = szA[0]
  kolA = szA[1]

  #print (fitP)

  for i in range(brsA):
    iJelek = fitP.max()
    idxJelek = fitP.argmax()

    if fitAnak[i]<iJelek:
      fitP[idxJelek] = fitAnak[i]
      for j in range (kolP):
        P[idxJelek][j] = Anak[i][j]
  
  return [P,fitP]

fitAnak = fungsiObjectif(AnakM,nodelist)
print("P :",P)
print("AnakM :",AnakM)
print("fitP :",fitP)
print("fitAnak :",fitAnak)
P = Elitism (P,AnakM,fitP,fitAnak)
print("P :",P)
print("fitP :",fitP)

P : [[47 43 36 38 28 37 30 34  2 50 22  9 29  7 24 40 25 31 10 41 12 11 39 27
  26 14  5 17  6  3 18 19 51  1 42 45 49  4 23 20 33 32 48 21 35 16 44 15
   0  8 13 46]
 [19 47  4 41 28  2 32 13 39  0 46 23 14 40  1 33 25 45 50 44 22 15 43 12
  18 21 30 42 36 17  9 31 16  5  3  6  8 34 20 29 48 51 26 35 49  7 24 37
  10 11 27 38]
 [10 14 17  9 26 46  6 29 38  0 48 13 30 44  8 21 47  7 40 28 51  2 37 11
  49 43 33 35 22 19 20  5 41 34 23 25 16 50  1 12 36 32 45  4 39 18  3 31
  27 24 42 15]
 [32  3 29 48 17 31 49  2 20  4 33 27 40  5 19 11 43  0 34 51 13 12 44  7
  26 16  6 35 42 30 41 24 23 18 39 21 14  1 50 38 10  9 15 22 36 28 25 47
   8 45 37 46]
 [ 3 34 35 46 20 14 51 17 42  7 27 23 43 12 38 24 22 47 26 37  4 28 18 15
  48  9 21 11 16  0 19 40 29  6 25 50 32 30 33 36 44 45 10 39  2 13 49  5
   8 31 41  1]
 [46 31 40 41 11 51 28 10 25 43 14  9 37 33 44  4 39 49 22 38 36 42 17 15
  45 34 30  5 24 48 35 23  2 16  6 12  8  0 18 21 47 26 19 27 32  3 20 13
   7 50 29  1]
 [37  9 25  2  6 3

###Prosedur GA

In [10]:
#Inisialisai Parameter
PCX = 0.95
Pm = 0.01
ukuranPopulasi = 10
max_generasi = 5

#Inisialisasi Populasi

P = initPopulasi (ukuranPopulasi,jumlahLokasi)
print("P0 :",P)

#melakukan Evaluasi P

fitP = fungsiObjectif(P,nodelist)
print("fitness populasi awal :",fitP)

print("fitness terbaik awal :",fitP.min())
print("rute awal :",P[fitP.argmin()])

for i in range(max_generasi):
  Induk = seleksi(P,fitP)
  #print("Induk :",Induk)

  Anak = Induk

  rxo = random.random()

  if rxo < PCX:
    Anak = PMX(Induk)

    rm = random.random()
    if rm < Pm:
      Anak = MutasiSwap(Anak)

    fitAnak = fungsiObjectif(Anak,nodelist)
    #print("fitAnak :",fitAnak)

    [P,fitP] = Elitism (P,Anak,fitP,fitAnak)

print("fitness populasi akhir :",fitP)
print("fitness akhir :",fitP.min())
print("rute akhir :",P[fitP.argmin()])

P0 : [[39 26  7 16 44 45  1 23 13 18  3 49 40 37 42 29 20 17  0  8 32 47  4 50
  11 51 38 19  9  5  2 41 46  6 24 22 15 21 14 33 12 28 48 25 34 35 10 36
  27 43 31 30]
 [47  5 39 37 15  8 13  3  1 20 25 19 34 42 40  2 30 45 32 27 11 14 31 50
  35  6 33  4 28 10  0 29 36 22 26 49 44 12 24  9 18  7 16 46 51 41 17 23
  21 48 43 38]
 [ 7 17 30 12 10 26  2 39  8 21 15  6 40  9 31 43  3 34 46  4 48 24 25 45
  22 13 42 20  0 27 37 35 49  1 51 19 47 18 23 14 50 38 36 44  5 41 16 32
  11 29 33 28]
 [34 46 29  6 26 40 25 36 16 33  3  0 31 45 49  1 48  2 15 27 44 18  9  4
  51 47 28 11 43  5 50  8 14 17 39 12 10 20 32 21 24 22 38 19 37 42 13 23
   7 35 41 30]
 [25  7 10 30 33 40 27  6  9 23 14 19 38 51 39  0 34 43 18 37  3 12  4 26
  17  1 28 45 49 44 29 21 47 24 13 11 16 15 50 36  2 42 35 48 22 41  8 32
  20 31 46  5]
 [16 10  4 48 51 17 35 13 41  2 27  9 24 21 23  0  8 39 36 12 33 45  7  6
   3  1 38 40 46 25 14 30 29 49 34 26 20 42 22 43 50 19 11  5 28 31 15 18
  44 37 47 32]
 [24 46 47 15 39 

#DATABASE ch150

In [11]:
# Open input file
infile = open('ch150.tsp', 'r')

# Read instance header
Name = infile.readline().strip().split()[1] # NAME
FileType = infile.readline().strip().split()[1] # TYPE
Comment = infile.readline().strip().split()[1] # COMMENT
Dimension = infile.readline().strip().split()[1] # DIMENSION
EdgeWeightType = infile.readline().strip().split()[1] # EDGE_WEIGHT_TYPE
infile.readline()

# Read node list
nodelist = []
N = int(Dimension)
for i in range(0, N):
    x,y = infile.readline().strip().split()[1:]
    nodelist.append([float(x), float(y)])

# Close input file
infile.close()

print (nodelist)

[[37.4393516691, 541.2090699418], [612.1759508571, 494.3166877396], [38.1312338227, 353.1484581781], [53.4418081065, 131.484901365], [143.0606355347, 631.7200953923], [689.9451267256, 468.5354998742], [112.7478815786, 529.417757826], [141.4875865042, 504.818485571], [661.0513901702, 445.9375182115], [98.7899036592, 384.5926031158], [697.3881696597, 180.3962284275], [536.4894189738, 287.2279085051], [192.4067320507, 20.439405931], [282.7865258765, 229.8001556189], [240.8251726391, 281.51414372], [246.9281323057, 322.461332116], [649.7313216456, 62.3331575282], [352.96585626, 666.7873101942], [633.392367658, 534.9398453712], [488.311799404, 437.4869439948], [141.4039286509, 228.4325551488], [17.3632612602, 240.2407068508], [397.5586451389, 231.3591208928], [565.7853781464, 282.3858748974], [475.8975387047, 468.5392706317], [322.4224566559, 550.3165478233], [397.5586634023, 74.7588387765], [672.8618339396, 432.882640963], [571.2189680147, 530.261699153], [104.6531165914, 482.8224768783], 

In [12]:
for i in nodelist:
    for j in i:
        print(j,end = " ")
    print()

jumlahLokasi =  len(nodelist)   
print(jumlahLokasi)

37.4393516691 541.2090699418 
612.1759508571 494.3166877396 
38.1312338227 353.1484581781 
53.4418081065 131.484901365 
143.0606355347 631.7200953923 
689.9451267256 468.5354998742 
112.7478815786 529.417757826 
141.4875865042 504.818485571 
661.0513901702 445.9375182115 
98.7899036592 384.5926031158 
697.3881696597 180.3962284275 
536.4894189738 287.2279085051 
192.4067320507 20.439405931 
282.7865258765 229.8001556189 
240.8251726391 281.51414372 
246.9281323057 322.461332116 
649.7313216456 62.3331575282 
352.96585626 666.7873101942 
633.392367658 534.9398453712 
488.311799404 437.4869439948 
141.4039286509 228.4325551488 
17.3632612602 240.2407068508 
397.5586451389 231.3591208928 
565.7853781464 282.3858748974 
475.8975387047 468.5392706317 
322.4224566559 550.3165478233 
397.5586634023 74.7588387765 
672.8618339396 432.882640963 
571.2189680147 530.261699153 
104.6531165914 482.8224768783 
356.7098388794 67.6477131712 
400.4070255527 253.6794479997 
282.3036243109 426.8380500923 

###Inisialisasi Populasi secara acak

###Array P diinisialisasi sebagai array integer

###Solusi awal dibuat dengan random permutation


In [13]:
def initPopulasi(ukuranPopulasi,jumlahLokasi):
  P = np.empty((ukuranPopulasi,jumlahLokasi))
  P = P.astype('int')
  for i in range(ukuranPopulasi):
    I = np.random.permutation(jumlahLokasi)
    for j in range(jumlahLokasi):
      P[i][j]=I[j]
  return P

ukuranPopulasi = 50
P = initPopulasi (ukuranPopulasi,jumlahLokasi)
print("Inisialisasi Populasi : ",P)

Inisialisasi Populasi :  [[ 89  43  14 ... 102  93 137]
 [124 149  26 ...  94 144  60]
 [106 122 121 ... 108  90  50]
 ...
 [ 49 102  75 ... 104  55 146]
 [109 100 129 ...  52 133 147]
 [ 19  33  95 ... 135 106  13]]


###Membuat Fungsi Objektif

###Jarak yang diukur adalah Jarak Euclidian

In [14]:
def fungsiObjectif(populasi,nodelist):
  sz = populasi.shape
  ukuranPopulasi = sz[0]
  jumlahLokasi = sz[1]

  matrikJarak = np.empty((ukuranPopulasi))
  matrikJarak = matrikJarak.astype('float')
  n = len(nodelist)

  for i in range(ukuranPopulasi):
    jarak = 0
    for j in range(n-1):
      jrkX = nodelist[populasi[i][j]][0]-nodelist[populasi[i][j+1]][0]
      jrkY = nodelist[populasi[i][j]][1]-nodelist[populasi[i][j+1]][1]
      d = np.sqrt(jrkX**2 + jrkY**2 )   
      jarak = jarak  + d
      
    dn =  np.sqrt((nodelist[populasi[i][n-1]][0]-nodelist[populasi[i][0]][0])**2+ (nodelist[populasi[i][n-1]][1]-nodelist[populasi[i][0]][1])**2 )
    jarak = jarak  + dn
    matrikJarak[i] = jarak

  return matrikJarak

fitP = fungsiObjectif(P,nodelist)
print(fitP)

[52996.67185389 53568.31541799 53017.22795706 55013.67094106
 53014.5618426  55120.94997935 55441.68328009 53603.55748528
 55517.07605195 53761.24065225 55477.71695624 52619.59316002
 53486.2744464  54696.48887198 52761.42440433 54727.34286211
 55242.14574515 52930.42825069 56025.41274058 56913.3229785
 56386.66597485 51444.55199017 53960.89010501 51685.81234999
 53695.63682172 55262.29834105 56467.50144988 51076.37520671
 55735.42116538 56986.64939218 57877.23314248 52252.59956655
 55167.88918074 52186.62957168 55940.32609324 54518.11744836
 55751.52257765 52327.35700826 54197.35742968 55266.01382341
 55967.58934015 55373.54389799 53738.07974809 57294.75476088
 52502.79566888 53955.41091556 54008.00926604 52876.75041011
 56736.87225172 54989.64757067]


###Seleksi menggunakan Metode Tournamen

###Ukuran Tournamen k = 2

###Jumlah Induk yang dipilih adalah 2

In [15]:
def seleksi (P,fsObj):
  jmlInduk = 2
  sz = P.shape
  ukuranPopulasi = sz[0]
  jumlahLokasi = sz[1]

  Induk = np.empty((jmlInduk,jumlahLokasi))
  Induk = Induk.astype('int')
  
  for i in range (2):
    #memilih dua individu secara acak 
    r1 = random.randint(0,ukuranPopulasi-1)
    r2 = random.randint(0,ukuranPopulasi-1)
    
    if  fsObj[r1] < fsObj [r2]:
      for j in range(jumlahLokasi):
        Induk [i][j] = P[r1][j]
    else:
      for j in range(jumlahLokasi):
        Induk [i][j] = P[r2][j]
  return Induk

Induk = seleksi(P,fitP)
print(Induk)

[[ 82  37  51 129 114  95 143 130  98  76 123  20  28  83 136 128  36 131
  137  73  68 141 107  77  99 144  26  27  89  61  31  56 124  70 148   3
  138  45 108  93  62   2  53  71 132  66  38  52 102  34   8  17 117  35
  120  12  39  64  23  40  97   1  54 116   4   7  43  41 147 112  67  32
  118  88  30 100  78 133 127 105 101  46  15 113  18 134 145  22  21  72
   75  25 149  55   6  65  80 125  87  63  42  86  69   9 104  60  19 142
   16  44  81 135 139  24  96  92  58  90  50  48 109 140  13  11 106  33
  115 126 122   0 103 119  57 146 111  10  49  47  29 110   5  74 121  94
   84  79  91  14  85  59]
 [ 34 117   8  13 129  74  69 135  73   6 113 111 126  46  27 140 148  70
  143 112  76  72   4  52 101  66  19  10  21  57  22  54 124  15  78  85
   64  95  48  53  40  37  84 107 130  30   7  51  32 100  65  12  59  79
  114  35  45 105  90  68  97  77 149 141 139  99  98   0  39  75 116  29
   55   1  49 144 103  18   2  92  17  20 132  14  71  96  26  47  38 115
   91  43  

###Rekombinasi menggunakan Metode Order Crossover (OX) Jumlah anak yang dihasilkan adalah 2
###Crossover 

In [16]:
def PMX(Induk):
  Induk = seleksi(P,fitP)
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  I1 = np.empty((kol))
  I2 = np.empty((kol))
  A1 = np.empty((kol))
  A2 = np.empty((kol))
  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  for i in range(kol):
    I1[i]=Induk[0][i]
    I2[i]=Induk[1][i]

  r1 = random.randint(1,kol-2)

  for i0 in range(r1): 
    A1[i0] = I1[i0]
    A2[i0] = I2[i0]

  batasCek1 = r1
  batasCek2 = r1

  for i in range(kol):
    m = (i+r1)%kol

    n1 = I1[m] 
    n2 = I2[m]

    #mengecek apakah Lokasi tertentu sudah ada di anak

    idxAda1 = 0
    idxAda2 = 0
    for j1 in range(batasCek1): 
      
      if batasCek1>(kol):
        idxAda1 = 1

      if A1[j1] == n2: 
        idxAda1 = 1
            
    for j2 in range(batasCek2): 
      
      if batasCek2>(kol):
        idxAda2 = 1

      if A2[j2] == n1: 
        idxAda2 = 1

    if idxAda1 == 0:
      A1[batasCek1] = n2
      batasCek1 = batasCek1 +1
   
    if idxAda2 == 0:
      A2[batasCek2] = n1
      batasCek2 = batasCek2 +1
   
  for i in range(kol):
    Anak[0][i]=A1[i]
    Anak[1][i]=A2[i]

  return Anak

AnakCX = PMX(Induk)
print("Anak :",AnakCX)

Anak : [[ 34 117   8  13 129  74  69 135  73   6 113 111 126  46  27 140 148  70
  143 112  76  72   4  52 101  66  19  10  21  57  22  54 124  15  78  85
   64  48  92   9 142 110  63  51  11 100 131  62 145  24  83  43  23 119
   36  44 141 133  98  58  81  18  65  86  32 104  91  87  89  94  96  20
   84 137  41  71  82 134  80  33 105  55  17 136 120  95   3   2   1 144
   47  28 139 125  30   0  35 121 149  93 102 127  38  53 123  40  99 114
   39  49  60 147  25 132  14  68 130  77  26 103  50   5 115 116  45  56
   79  59 109  88 138 118  90 122  29  67 108 106   7  31  97  12  61  16
   75 128 146 107  37  42]
 [ 45  46  56  79  59 109  88 138 143 118  73  76  27 113 101  90 122 140
   29  67 108 106   7 117  31  97  12  72  61  15  16  75 128 146 107  37
   42  95  48  53  40  84 130  30  51  32 100  65 114  35 105  68  77 149
  141 139  99  98   0  39 116  55   1  49 144 103  18   2  92  17  20 132
   14  71  96  26  47  38 115  91  43  23 134  41  36 119  86  93 123  62
   8

###Mutasi dengan Swap

###Index Lokasi yang di Swap pada kedua anak sama

In [17]:
def MutasiSwap(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  Anak = Induk

  r1 = random.randint(0,kol-1)
  r2 = random.randint(0,kol-1)

  while r1 == r2:
    r2 = random.randint(0,kol-1)
  
  if r1 < r2:
    rs1 = r1
    rs2 = r2
  else:
    rs1 = r2
    rs2 = r1

  I1rs1 = Induk [0][rs1]
  I1rs2 = Induk [0][rs2]
  I2rs1 = Induk [1][rs1]
  I2rs2 = Induk [1][rs2]

  Anak[0][rs1] = I1rs2
  Anak[0][rs2] = I1rs1
  Anak[1][rs1] = I2rs2
  Anak[1][rs2] = I2rs1

  return Anak

print("AnakCX :",AnakCX)
AnakM = MutasiSwap(AnakCX)
print("AnakM :",AnakM)

AnakCX : [[ 34 117   8  13 129  74  69 135  73   6 113 111 126  46  27 140 148  70
  143 112  76  72   4  52 101  66  19  10  21  57  22  54 124  15  78  85
   64  48  92   9 142 110  63  51  11 100 131  62 145  24  83  43  23 119
   36  44 141 133  98  58  81  18  65  86  32 104  91  87  89  94  96  20
   84 137  41  71  82 134  80  33 105  55  17 136 120  95   3   2   1 144
   47  28 139 125  30   0  35 121 149  93 102 127  38  53 123  40  99 114
   39  49  60 147  25 132  14  68 130  77  26 103  50   5 115 116  45  56
   79  59 109  88 138 118  90 122  29  67 108 106   7  31  97  12  61  16
   75 128 146 107  37  42]
 [ 45  46  56  79  59 109  88 138 143 118  73  76  27 113 101  90 122 140
   29  67 108 106   7 117  31  97  12  72  61  15  16  75 128 146 107  37
   42  95  48  53  40  84 130  30  51  32 100  65 114  35 105  68  77 149
  141 139  99  98   0  39 116  55   1  49 144 103  18   2  92  17  20 132
   14  71  96  26  47  38 115  91  43  23 134  41  36 119  86  93 123  62
  

###Elitism (steady state replacement)

In [18]:
def Elitism(P,Anak,fitP,fitAnak):
  szP = P.shape
  brsP = szP[0]
  kolP = szP[1]
  szA = Anak.shape
  brsA = szA[0]
  kolA = szA[1]

  #print (fitP)

  for i in range(brsA):
    iJelek = fitP.max()
    idxJelek = fitP.argmax()

    if fitAnak[i]<iJelek:
      fitP[idxJelek] = fitAnak[i]
      for j in range (kolP):
        P[idxJelek][j] = Anak[i][j]
  
  return [P,fitP]

fitAnak = fungsiObjectif(AnakM,nodelist)
print("P :",P)
print("AnakM :",AnakM)
print("fitP :",fitP)
print("fitAnak :",fitAnak)
P = Elitism (P,AnakM,fitP,fitAnak)
print("P :",P)
print("fitP :",fitP)

P : [[ 89  43  14 ... 102  93 137]
 [124 149  26 ...  94 144  60]
 [106 122 121 ... 108  90  50]
 ...
 [ 49 102  75 ... 104  55 146]
 [109 100 129 ...  52 133 147]
 [ 19  33  95 ... 135 106  13]]
AnakM : [[ 34 117   8  13 129  74  69 135  73   6 113 111 126  46  27 140  40  70
  143 112  76  72   4  52 101  66  19  10  21  57  22  54 124  15  78  85
   64  48  92   9 142 110  63  51  11 100 131  62 145  24  83  43  23 119
   36  44 141 133  98  58  81  18  65  86  32 104  91  87  89  94  96  20
   84 137  41  71  82 134  80  33 105  55  17 136 120  95   3   2   1 144
   47  28 139 125  30   0  35 121 149  93 102 127  38  53 123 148  99 114
   39  49  60 147  25 132  14  68 130  77  26 103  50   5 115 116  45  56
   79  59 109  88 138 118  90 122  29  67 108 106   7  31  97  12  61  16
   75 128 146 107  37  42]
 [ 45  46  56  79  59 109  88 138 143 118  73  76  27 113 101  90   3 140
   29  67 108 106   7 117  31  97  12  72  61  15  16  75 128 146 107  37
   42  95  48  53  40  84 130

###Prosedur GA

In [19]:
#Inisialisai Parameter
PCX = 0.95
Pm = 0.05
ukuranPopulasi = 50
max_generasi = 10

#Inisialisasi Populasi

P = initPopulasi (ukuranPopulasi,jumlahLokasi)
print("P0 :",P)

#melakukan Evaluasi P

fitP = fungsiObjectif(P,nodelist)
print("fitness populasi awal :",fitP)

print("fitness terbaik awal :",fitP.min())
print("rute awal :",P[fitP.argmin()])

for i in range(max_generasi):
  Induk = seleksi(P,fitP)
  #print("Induk :",Induk)

  Anak = Induk

  rxo = random.random()

  if rxo < PCX:
    Anak = PMX(Induk)

    rm = random.random()
    if rm < Pm:
      Anak = MutasiSwap(Anak)

    fitAnak = fungsiObjectif(Anak,nodelist)
    #print("fitAnak :",fitAnak)

    [P,fitP] = Elitism (P,Anak,fitP,fitAnak)

print("fitness populasi akhir :",fitP)
print("fitness akhir :",fitP.min())
print("rute akhir :",P[fitP.argmin()])

P0 : [[109 133  72 ...  74  24  66]
 [ 86  69  44 ... 104 132  80]
 [ 73  89 113 ...  90 142 103]
 ...
 [ 50  74 133 ...  68  62 114]
 [129  47  85 ... 143  56 123]
 [ 90  51  52 ...  62 112   2]]
fitness populasi awal : [53100.05344848 54805.47851237 53534.89569317 54977.80012193
 53846.16755817 56065.39106103 54131.29537436 55618.95063705
 54759.69921393 53815.9998159  52497.22013439 56191.26733836
 53856.89589943 56504.45945787 55659.62854849 54851.78567793
 57120.51399605 53941.05387066 52436.11739206 56039.19167527
 49650.1555808  51025.87320697 52389.53651078 53043.72922087
 51623.71086381 53981.68332644 53916.53720386 53718.81968586
 56240.74607281 55231.45136399 53419.29119994 54085.83371688
 52690.55785079 51050.93922071 51183.19871225 53669.69799572
 55639.00028248 53468.86687574 52203.59141312 53513.87259029
 51694.15330056 49409.0937149  54843.85913108 53606.30420862
 51689.88430908 49085.19820376 55281.0951049  52273.03577244
 53286.63313538 49460.3210849 ]
fitness terbaik

#DATABASE kroA100

In [20]:
# Open input file
infile = open('kroA100.tsp', 'r')

# Read instance header
Name = infile.readline().strip().split()[1] # NAME
FileType = infile.readline().strip().split()[1] # TYPE
Comment = infile.readline().strip().split()[1] # COMMENT
Dimension = infile.readline().strip().split()[1] # DIMENSION
EdgeWeightType = infile.readline().strip().split()[1] # EDGE_WEIGHT_TYPE
infile.readline()

# Read node list
nodelist = []
N = int(Dimension)
for i in range(0, N):
    x,y = infile.readline().strip().split()[1:]
    nodelist.append([float(x), float(y)])

# Close input file
infile.close()

print (nodelist)

[[1380.0, 939.0], [2848.0, 96.0], [3510.0, 1671.0], [457.0, 334.0], [3888.0, 666.0], [984.0, 965.0], [2721.0, 1482.0], [1286.0, 525.0], [2716.0, 1432.0], [738.0, 1325.0], [1251.0, 1832.0], [2728.0, 1698.0], [3815.0, 169.0], [3683.0, 1533.0], [1247.0, 1945.0], [123.0, 862.0], [1234.0, 1946.0], [252.0, 1240.0], [611.0, 673.0], [2576.0, 1676.0], [928.0, 1700.0], [53.0, 857.0], [1807.0, 1711.0], [274.0, 1420.0], [2574.0, 946.0], [178.0, 24.0], [2678.0, 1825.0], [1795.0, 962.0], [3384.0, 1498.0], [3520.0, 1079.0], [1256.0, 61.0], [1424.0, 1728.0], [3913.0, 192.0], [3085.0, 1528.0], [2573.0, 1969.0], [463.0, 1670.0], [3875.0, 598.0], [298.0, 1513.0], [3479.0, 821.0], [2542.0, 236.0], [3955.0, 1743.0], [1323.0, 280.0], [3447.0, 1830.0], [2936.0, 337.0], [1621.0, 1830.0], [3373.0, 1646.0], [1393.0, 1368.0], [3874.0, 1318.0], [938.0, 955.0], [3022.0, 474.0], [2482.0, 1183.0], [3854.0, 923.0], [376.0, 825.0], [2519.0, 135.0], [2945.0, 1622.0], [953.0, 268.0], [2628.0, 1479.0], [2097.0, 981.0], [

In [21]:
for i in nodelist:
    for j in i:
        print(j,end = " ")
    print()

jumlahLokasi =  len(nodelist)   
print(jumlahLokasi)

1380.0 939.0 
2848.0 96.0 
3510.0 1671.0 
457.0 334.0 
3888.0 666.0 
984.0 965.0 
2721.0 1482.0 
1286.0 525.0 
2716.0 1432.0 
738.0 1325.0 
1251.0 1832.0 
2728.0 1698.0 
3815.0 169.0 
3683.0 1533.0 
1247.0 1945.0 
123.0 862.0 
1234.0 1946.0 
252.0 1240.0 
611.0 673.0 
2576.0 1676.0 
928.0 1700.0 
53.0 857.0 
1807.0 1711.0 
274.0 1420.0 
2574.0 946.0 
178.0 24.0 
2678.0 1825.0 
1795.0 962.0 
3384.0 1498.0 
3520.0 1079.0 
1256.0 61.0 
1424.0 1728.0 
3913.0 192.0 
3085.0 1528.0 
2573.0 1969.0 
463.0 1670.0 
3875.0 598.0 
298.0 1513.0 
3479.0 821.0 
2542.0 236.0 
3955.0 1743.0 
1323.0 280.0 
3447.0 1830.0 
2936.0 337.0 
1621.0 1830.0 
3373.0 1646.0 
1393.0 1368.0 
3874.0 1318.0 
938.0 955.0 
3022.0 474.0 
2482.0 1183.0 
3854.0 923.0 
376.0 825.0 
2519.0 135.0 
2945.0 1622.0 
953.0 268.0 
2628.0 1479.0 
2097.0 981.0 
890.0 1846.0 
2139.0 1806.0 
2421.0 1007.0 
2290.0 1810.0 
1115.0 1052.0 
2588.0 302.0 
327.0 265.0 
241.0 341.0 
1917.0 687.0 
2991.0 792.0 
2573.0 599.0 
19.0 674.0 
3911.0 1

###Inisialisasi Populasi secara acak

###Array P diinisialisasi sebagai array integer

###Solusi awal dibuat dengan random permutation


In [22]:
def initPopulasi(ukuranPopulasi,jumlahLokasi):
  P = np.empty((ukuranPopulasi,jumlahLokasi))
  P = P.astype('int')
  for i in range(ukuranPopulasi):
    I = np.random.permutation(jumlahLokasi)
    for j in range(jumlahLokasi):
      P[i][j]=I[j]
  return P

ukuranPopulasi = 50
P = initPopulasi (ukuranPopulasi,jumlahLokasi)
print("Inisialisasi Populasi : ",P)

Inisialisasi Populasi :  [[99 63 95 ... 77 23 42]
 [62 67  6 ...  8 60 47]
 [66  5 20 ... 98  0 92]
 ...
 [55 56 18 ... 74  1 25]
 [51 81 67 ...  1 20 54]
 [ 2 99 56 ... 48 39  1]]


###Membuat Fungsi Objektif

###Jarak yang diukur adalah Jarak Euclidian

In [23]:
def fungsiObjectif(populasi,nodelist):
  sz = populasi.shape
  ukuranPopulasi = sz[0]
  jumlahLokasi = sz[1]

  matrikJarak = np.empty((ukuranPopulasi))
  matrikJarak = matrikJarak.astype('float')
  n = len(nodelist)

  for i in range(ukuranPopulasi):
    jarak = 0
    for j in range(n-1):
      jrkX = nodelist[populasi[i][j]][0]-nodelist[populasi[i][j+1]][0]
      jrkY = nodelist[populasi[i][j]][1]-nodelist[populasi[i][j+1]][1]
      d = np.sqrt(jrkX**2 + jrkY**2 )   
      jarak = jarak  + d
      
    dn =  np.sqrt((nodelist[populasi[i][n-1]][0]-nodelist[populasi[i][0]][0])**2+ (nodelist[populasi[i][n-1]][1]-nodelist[populasi[i][0]][1])**2 )
    jarak = jarak  + dn
    matrikJarak[i] = jarak

  return matrikJarak

fitP = fungsiObjectif(P,nodelist)
print(fitP)

[168875.91138824 173266.60196788 164465.94806898 161696.03469265
 182028.85575812 151683.04190506 168115.35469874 169688.62965952
 170503.43934277 173811.10105156 161361.05635004 182691.24168686
 163418.22051603 174191.18555486 168774.14490596 179400.07231756
 181168.36069643 189870.01519976 168579.18370239 176440.70729466
 166347.1253564  163792.33871856 179277.31115653 187864.14046868
 160174.51075626 174986.52812858 170718.58642337 160028.28622176
 173306.64729359 184434.33735342 168202.64633132 159330.75140295
 181724.35079319 177297.12462796 154146.53132506 169423.64423164
 177267.11409263 167659.0001572  173177.14927169 163098.11712667
 158610.89489452 168532.13152498 154589.73911289 169914.06663417
 162360.49167733 183064.80196371 173650.55548404 173582.78975389
 157571.94942562 175684.53198489]


###Seleksi menggunakan Metode Tournamen

###Ukuran Tournamen k = 2

###Jumlah Induk yang dipilih adalah 2

In [24]:
def seleksi (P,fsObj):
  jmlInduk = 2
  sz = P.shape
  ukuranPopulasi = sz[0]
  jumlahLokasi = sz[1]

  Induk = np.empty((jmlInduk,jumlahLokasi))
  Induk = Induk.astype('int')
  
  for i in range (2):
    #memilih dua individu secara acak 
    r1 = random.randint(0,ukuranPopulasi-1)
    r2 = random.randint(0,ukuranPopulasi-1)
    
    if  fsObj[r1] < fsObj [r2]:
      for j in range(jumlahLokasi):
        Induk [i][j] = P[r1][j]
    else:
      for j in range(jumlahLokasi):
        Induk [i][j] = P[r2][j]
  return Induk

Induk = seleksi(P,fitP)
print(Induk)

[[51 81 67 73 78 15 74  7 28 16  4 72 22 93 57 89 29 56 66 43 71 46 80  8
  96 55 91 60 63 58 18 41 52 88 14 24 92  6 19 77 10 90 40  0  3 69 17 30
  34 86 26 95 75 85 27 44 79 83 37 61 47 45 48 13 21 42 70 65  5  2 38 32
  50 99 23 84 94 39 11  9 35 49 76 87 68 98 31 64 59 12 82 97 33 53 62 25
  36  1 20 54]
 [ 9 43 88 29 11  5  2 35 76 99 70 20 10 89 54 61 93  6 28 31 44 98 38 66
  71 34  0 62 92 17 57 79 56 95 55 83 58 46 12 40 75 49 84 77 67 80 22 14
  50 47 74 90 63 68 69 25 78 15 13 81 82 27 85 87  8 96 72 59 30 41 53  3
  24 48 19 52 37  7 65 21 36 91 60 26 97 18 64 33 51  4 32  1 73 16 86 94
  42 45 23 39]]


###Rekombinasi menggunakan Metode Order Crossover (OX) Jumlah anak yang dihasilkan adalah 2
###Crossover 

In [25]:
def PMX(Induk):
  Induk = seleksi(P,fitP)
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  I1 = np.empty((kol))
  I2 = np.empty((kol))
  A1 = np.empty((kol))
  A2 = np.empty((kol))
  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  for i in range(kol):
    I1[i]=Induk[0][i]
    I2[i]=Induk[1][i]

  r1 = random.randint(1,kol-2)

  for i0 in range(r1): 
    A1[i0] = I1[i0]
    A2[i0] = I2[i0]

  batasCek1 = r1
  batasCek2 = r1

  for i in range(kol):
    m = (i+r1)%kol

    n1 = I1[m] 
    n2 = I2[m]

    #mengecek apakah Lokasi tertentu sudah ada di anak

    idxAda1 = 0
    idxAda2 = 0
    for j1 in range(batasCek1): 
      
      if batasCek1>(kol):
        idxAda1 = 1

      if A1[j1] == n2: 
        idxAda1 = 1
            
    for j2 in range(batasCek2): 
      
      if batasCek2>(kol):
        idxAda2 = 1

      if A2[j2] == n1: 
        idxAda2 = 1

    if idxAda1 == 0:
      A1[batasCek1] = n2
      batasCek1 = batasCek1 +1
   
    if idxAda2 == 0:
      A2[batasCek2] = n1
      batasCek2 = batasCek2 +1
   
  for i in range(kol):
    Anak[0][i]=A1[i]
    Anak[1][i]=A2[i]

  return Anak

AnakCX = PMX(Induk)
print("Anak :",AnakCX)

Anak : [[99 63 95  0 79 24 40 55 12 38 26  4 16 90 22 42 52 10 89 46 75 49 28 51
  14 68 81 15 41 29 17 83 71 62 19 84 88 34 57 80  5  3 72 85 92 58 69 76
  93  1 70 45 33 74 47 37 23  7 61  8 82  9 64  6 87 73 39 60 20 13 94 53
  11 77 43 30 54 18 36 65 96 67 21 44 27 56 35 25 91 86 48 66 59 78 50  2
  31 32 97 98]
 [86 48 66 59 78 50  2 31 32 97 98 13 16  1 58 34 67 10 47  9 18 54 51 60
  37 57 44 39 82 49 46 14 96 68 65 74 84 89 17 29  5 75 93 72 71 11 15 62
   6 91 73 28 85 53 61 88  7 90 92 25 45 64 21 87  8  4 35 20 76 22 19 81
  43 94  3 80 70 69 36 27 56 52 83 30 41 33 77 23 42 99 63 95  0 79 24 40
  55 12 38 26]]


###Mutasi dengan Swap

###Index Lokasi yang di Swap pada kedua anak sama

In [26]:
def MutasiSwap(Induk):
  sz = Induk.shape
  brs = sz[0]
  kol = sz[1]

  Anak = np.empty((2,kol))
  Anak = Anak.astype('int')

  Anak = Induk

  r1 = random.randint(0,kol-1)
  r2 = random.randint(0,kol-1)

  while r1 == r2:
    r2 = random.randint(0,kol-1)
  
  if r1 < r2:
    rs1 = r1
    rs2 = r2
  else:
    rs1 = r2
    rs2 = r1

  I1rs1 = Induk [0][rs1]
  I1rs2 = Induk [0][rs2]
  I2rs1 = Induk [1][rs1]
  I2rs2 = Induk [1][rs2]

  Anak[0][rs1] = I1rs2
  Anak[0][rs2] = I1rs1
  Anak[1][rs1] = I2rs2
  Anak[1][rs2] = I2rs1

  return Anak

print("AnakCX :",AnakCX)
AnakM = MutasiSwap(AnakCX)
print("AnakM :",AnakM)

AnakCX : [[99 63 95  0 79 24 40 55 12 38 26  4 16 90 22 42 52 10 89 46 75 49 28 51
  14 68 81 15 41 29 17 83 71 62 19 84 88 34 57 80  5  3 72 85 92 58 69 76
  93  1 70 45 33 74 47 37 23  7 61  8 82  9 64  6 87 73 39 60 20 13 94 53
  11 77 43 30 54 18 36 65 96 67 21 44 27 56 35 25 91 86 48 66 59 78 50  2
  31 32 97 98]
 [86 48 66 59 78 50  2 31 32 97 98 13 16  1 58 34 67 10 47  9 18 54 51 60
  37 57 44 39 82 49 46 14 96 68 65 74 84 89 17 29  5 75 93 72 71 11 15 62
   6 91 73 28 85 53 61 88  7 90 92 25 45 64 21 87  8  4 35 20 76 22 19 81
  43 94  3 80 70 69 36 27 56 52 83 30 41 33 77 23 42 99 63 95  0 79 24 40
  55 12 38 26]]
AnakM : [[99 63 95  0 79 24 40 55 12 38 26  4 16 90 22 42 30 10 89 46 75 49 28 51
  14 68 81 15 41 29 17 83 71 62 19 84 88 34 57 80  5  3 72 85 92 58 69 76
  93  1 70 45 33 74 47 37 23  7 61  8 82  9 64  6 87 73 39 60 20 13 94 53
  11 77 43 52 54 18 36 65 96 67 21 44 27 56 35 25 91 86 48 66 59 78 50  2
  31 32 97 98]
 [86 48 66 59 78 50  2 31 32 97 98 13 16  1 58 34

###Elitism (steady state replacement)

In [27]:
def Elitism(P,Anak,fitP,fitAnak):
  szP = P.shape
  brsP = szP[0]
  kolP = szP[1]
  szA = Anak.shape
  brsA = szA[0]
  kolA = szA[1]

  #print (fitP)

  for i in range(brsA):
    iJelek = fitP.max()
    idxJelek = fitP.argmax()

    if fitAnak[i]<iJelek:
      fitP[idxJelek] = fitAnak[i]
      for j in range (kolP):
        P[idxJelek][j] = Anak[i][j]
  
  return [P,fitP]

fitAnak = fungsiObjectif(AnakM,nodelist)
print("P :",P)
print("AnakM :",AnakM)
print("fitP :",fitP)
print("fitAnak :",fitAnak)
P = Elitism (P,AnakM,fitP,fitAnak)
print("P :",P)
print("fitP :",fitP)

P : [[99 63 95 ... 77 23 42]
 [62 67  6 ...  8 60 47]
 [66  5 20 ... 98  0 92]
 ...
 [55 56 18 ... 74  1 25]
 [51 81 67 ...  1 20 54]
 [ 2 99 56 ... 48 39  1]]
AnakM : [[99 63 95  0 79 24 40 55 12 38 26  4 16 90 22 42 30 10 89 46 75 49 28 51
  14 68 81 15 41 29 17 83 71 62 19 84 88 34 57 80  5  3 72 85 92 58 69 76
  93  1 70 45 33 74 47 37 23  7 61  8 82  9 64  6 87 73 39 60 20 13 94 53
  11 77 43 52 54 18 36 65 96 67 21 44 27 56 35 25 91 86 48 66 59 78 50  2
  31 32 97 98]
 [86 48 66 59 78 50  2 31 32 97 98 13 16  1 58 34 80 10 47  9 18 54 51 60
  37 57 44 39 82 49 46 14 96 68 65 74 84 89 17 29  5 75 93 72 71 11 15 62
   6 91 73 28 85 53 61 88  7 90 92 25 45 64 21 87  8  4 35 20 76 22 19 81
  43 94  3 67 70 69 36 27 56 52 83 30 41 33 77 23 42 99 63 95  0 79 24 40
  55 12 38 26]]
fitP : [168875.91138824 173266.60196788 164465.94806898 161696.03469265
 182028.85575812 151683.04190506 168115.35469874 169688.62965952
 170503.43934277 173811.10105156 161361.05635004 182691.24168686
 163418

###Prosedur GA

In [28]:
#Inisialisai Parameter
PCX = 0.95
Pm = 0.01
ukuranPopulasi = 50
max_generasi = 975

#Inisialisasi Populasi

P = initPopulasi (ukuranPopulasi,jumlahLokasi)
print("P0 :",P)

#melakukan Evaluasi P

fitP = fungsiObjectif(P,nodelist)
print("fitness populasi awal :",fitP)

print("fitness terbaik awal :",fitP.min())
print("rute awal :",P[fitP.argmin()])

for i in range(max_generasi):
  Induk = seleksi(P,fitP)
  #print("Induk :",Induk)

  Anak = Induk

  rxo = random.random()

  if rxo < PCX:
    Anak = PMX(Induk)

    rm = random.random()
    if rm < Pm:
      Anak = MutasiSwap(Anak)

    fitAnak = fungsiObjectif(Anak,nodelist)
    #print("fitAnak :",fitAnak)

    [P,fitP] = Elitism (P,Anak,fitP,fitAnak)

print("fitness populasi akhir :",fitP)
print("fitness akhir :",fitP.min())
print("rute akhir :",P[fitP.argmin()])

P0 : [[34 64 41 ... 47 14 52]
 [86 25 12 ... 11 37 85]
 [92 51 23 ... 84 18 21]
 ...
 [31 15 48 ... 75 22 35]
 [24 66 56 ... 53 13 42]
 [70 60 81 ... 35 29 93]]
fitness populasi awal : [185340.04935785 167686.72797748 170797.49292439 174431.88737669
 172873.92241182 173912.79996418 178351.17377963 155279.11922606
 168434.62584538 165616.83977387 168835.83228605 170204.47254498
 164362.41121045 171496.59821556 174366.23266875 153859.34493577
 197680.07744208 178750.02708233 187990.53182282 181702.69438873
 176854.00062955 162791.5284788  165185.35399686 171654.99364632
 170863.78781915 179846.39717034 163425.79624594 163770.96943994
 169787.7540492  167596.28962596 162856.98940092 170508.05826512
 186072.3136381  166119.55771924 158875.74514712 174165.26873671
 171123.92672372 176478.96401005 162336.3008771  196500.53335831
 173795.24413016 167650.86058653 173028.74211058 159003.17627206
 175904.49894503 168886.9224985  180283.34386791 174270.38470741
 173094.3290294  180796.73469485]
f